### PR TITLE
Removing the extra white space from the middle of street names

### LINKED ISSUE #69: whitespace in street name
*note:* this may be fixed in dev, the data below was taken from the production server 18 Mar '16 and I couldn't confirm because the dev server was being rebuilt at the time.

```
"street": "South Albany          Avenue",
```

```javascript
{
  "type": "Feature",
  "properties": {
    "id": "2d698c8c74484096a80758033b694967",
    "gid": "oa:address:2d698c8c74484096a80758033b694967",
    "layer": "address",
    "source": "oa",
    "name": "200 South Albany Avenue",
    "housenumber": "200",
    "street": "South Albany          Avenue",
    "country_a": "USA",
    "country": "United States",
    "region": "Florida",
    "region_a": "FL",
    "county": "Martin County",
    "locality": "Stuart",
    "neighbourhood": "Watermark Marina of Palm City",
    "confidence": 0.848,
    "label": "200 South Albany Avenue, Stuart, FL"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -80.256743,
      27.199085
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by avulfson17**
Fixes #69

### CODE REVIEW

**Comment by trescube** [comment]
:shipit:

**Comment by orangejulius** [comment]
LGTM

**Comment by trescube** [comment]
On second thought, this seems awfully professional (not your bad, @avulfson17), can it be done with lodash `.replace`s?

**Comment by trescube** [comment]
Scratch that, it's fine, the regex for multi-token in lodash would be pretty complex.

**Pull request merged**
