### PR TITLE
Don't generate name for Openaddresses records

### PR DESCRIPTION
**Pull request by orangejulius**
Combined with a similar change for the OSM importer, this will help with
pelias/pelias#168

### CODE REVIEW

**Comment by orangejulius** [comment]
I just realized this might help our index size considerably as well, since for OA the name field is basically completely duplicating data in the housenumber and street fields

**Comment by stephenkhess** [comment]
For backward compatibility, the API should be modified to generate the name field from the constituent parts, then the importer should be modified to not generate the name field.

**Comment by stephenkhess** [comment]
There is apparently a non-trivial amount of work in the API to do with this since `name` is the primary search field and this change would require searching in other fields.

**Comment by orangejulius** [comment]
This is getting old, so I'll close this PR, we can pick up the exploration later

**Pull request closed without merging**
