### PR TITLE
feat: add HTTP requests limiting on utils/ to avoid ban

### LINKED ISSUE #433: Sleep between HTTP requests to avoid ban
There is no countrywide data in OpenAddresses for Brazil, thus the solution I thought about is to download 27 states files. The openaddresses section in `pelias.json` is:

```json
"openaddresses": {
      "datapath": "/data/openaddresses",
      "files": [
        "br/ac/statewide.csv",
        "br/al/statewide.csv",
        "br/am/statewide.csv",
        "br/ap/statewide.csv",
        "br/ba/statewide.csv",
        "br/ce/statewide.csv",
        "br/df/statewide.csv",
        "br/es/statewide.csv",
        "br/go/statewide.csv",
        "br/ma/statewide.csv",
        "br/mg/statewide.csv",
        "br/ms/statewide.csv",
        "br/mt/statewide.csv",
        "br/pa/statewide.csv",
        "br/pb/statewide.csv",
        "br/pe/statewide.csv",
        "br/pi/statewide.csv",
        "br/pr/statewide.csv",
        "br/rj/statewide.csv",
        "br/rn/statewide.csv",
        "br/ro/statewide.csv",
        "br/rr/statewide.csv",
        "br/rs/statewide.csv",
        "br/sc/statewide.csv",
        "br/se/statewide.csv",
        "br/sp/statewide.csv",
        "br/to/statewide.csv"
      ]
    }
```

But, as there is no delay between the HTTP requests, only the first five ones are downloaded, and the following ones are rejected:

```bash
$ pelias download oa
info: [openaddresses-download] Attempting to download selected data files: br/ac/statewide.csv,br/al/statewide.csv,br/am/statewide.csv,br/ap/statewide.csv,br/ba/statewide.csv,br/ce/statewide.csv,br/df/statewide.csv,br/es/statewide.csv,br/go/statewide.csv,br/ma/statewide.csv,br/mg/statewide.csv,br/ms/statewide.csv,br/mt/statewide.csv,br/pa/statewide.csv,br/pb/statewide.csv,br/pe/statewide.csv,br/pi/statewide.csv,br/pr/statewide.csv,br/rj/statewide.csv,br/rn/statewide.csv,br/ro/statewide.csv,br/rr/statewide.csv,br/rs/statewide.csv,br/sc/statewide.csv,br/se/statewide.csv,br/sp/statewide.csv,br/to/statewide.csv
info: [openaddresses-download] Downloading br/ac/statewide.csv
info: [openaddresses-download] Downloading br/al/statewide.csv
info: [openaddresses-download] Downloading br/am/statewide.csv
info: [openaddresses-download] Downloading br/ap/statewide.csv
info: [openaddresses-download] Downloading br/ba/statewide.csv
warn: [openaddresses-download] failed to download https://results.openaddresses.io/latest/run/br/ap/statewide.zip: Error: Command failed: unzip -o -qq -d /data/openaddresses /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip
[/data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip or
        /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip.zip, and cannot find /data/openaddresses/br-ap-statewide1xjsSf4dlWvQJ.zip.ZIP, period.
...
```

Maybe solutions could be: 1. to make the process sleep for various seconds between every download from the same source, 2. to ignore the file if it has already been downloaded in `/data/openaddresses/` (ie. an option to force re-download or not).

Thanks a lot for reading, and please tell me if I can help in any way.

### PR DESCRIPTION
**Pull request by severo**
An attempt to fix #433.

### CODE REVIEW

**Comment by orangejulius** [comment]
@severo thanks for this PR.

It looks really good, and I especially like the refactoring to create very sensible objects for each of the downloads.

The [limited-request-queue](https://github.com/stevenvachon/limited-request-queue#installation) dependency requires Node.js 10 or greater. Pelias currently supports Node.js 8, however we're about to drop support for Node.js 8 as we [add support for Node.js 12](https://github.com/pelias/pelias/issues/800), so we'll have to wait to merge this until that happens.

**Comment by severo** [comment]
OK.

Note that I tried to apply the minimum changes, but is there a specific reason to call system tools like curl and unzip, instead of using node modules?

**Comment by orangejulius** [comment]
Yes, we found using node modules to be extremely slow (Pelias often has to download and decompress very large archive files).

To be honest, I don't think the project goals include supporting other platforms like Windows that would require us to move to native Node.js code for downloads.

**Comment by severo** [comment]
OK, thanks for the explanation.

**Comment by severo** [comment]
#435 replaces the [limited-request-queue](https://github.com/stevenvachon/limited-request-queue#installation) dependency by [bottleneck](https://www.npmjs.com/package/bottleneck), that supports Node.js 8 (and is 10 times more popular).

**Pull request closed without merging**
