### PR TITLE
ensure that sources end with ".csv"

### PR DESCRIPTION
**Pull request by missinglink**
Today I made the silly mistake of not adding the `.csv` suffix to 'files' in my `pelias.json`.
The result was very noisy and appeared to be a download issue.

This PR adds an additional check to ensure the `files` array entries end with `.csv` before attempting a download.

### CODE REVIEW

**Comment by missinglink** [comment]
```bash
./bin/download
2019-07-10T13:42:14.255Z - info: [openaddresses-download] Attempting to download selected data files: foo
2019-07-10T13:42:14.260Z - info: [openaddresses-download] Downloading foo
2019-07-10T13:42:14.260Z - warn: [openaddresses-download] invalid source foo: MUST end with '.csv'
2019-07-10T13:42:14.261Z - info: [download] All done!
```

with `missingFilesAreFatal=true`:
```bash
./bin/download
2019-07-10T13:42:57.389Z - info: [openaddresses-download] Attempting to download selected data files: foo
2019-07-10T13:42:57.394Z - info: [openaddresses-download] Downloading foo
2019-07-10T13:42:57.394Z - warn: [openaddresses-download] invalid source foo: MUST end with '.csv'
2019-07-10T13:42:57.394Z - error: [download] Failed to download data invalid source foo: MUST end with '.csv'
➜  openaddresses git:(download_filtered_source_suffix) echo $?
```

**Comment by orangejulius** [comment]
Yeah, we should do something to help our users here, many people have made this mistake.

Should we go a step further and just make the code append the `csv` extension if it's not there? That would "magically" fix the issue for people, which could be nice (or confusing).

**Comment by missinglink** [comment]
Hmm yea tough one, I think it's better to try to 'catch and warn' rather than trying to fix things, but if we could do that in a reliable way then I'd be cool with it :)

I'll merge this as-is and we can add correction magic in a future PR.

**Comment by orangejulius** [comment]
Makes sense to me

**Comment by orangejulius** [comment]
Thanks @aparshin, I have fixed this over in https://github.com/pelias/openaddresses/pull/430

**Pull request merged**
